services:
  db:
    image: postgres:17.2-bullseye
    container_name: timezone_pg
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timezone_django
    command: bash -c "chmod 755 /app/wait-for-it.sh && /app/wait-for-it.sh --host=db --port=5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
